### ISSUE TITLE
Error: jsdbAxios.defaults.baseURL.replaceAll is not a function

### ISSUE THREAD

**Issue by crazy4groovy** [javascriptdb/jsdb-sdk#1]
lib: `"@jsdb/sdk": "0.0.22"`
OS: Windows 10

```
import { functions, DatabaseArray, DatabaseMap, setServerUrl } from "@jsdb/sdk";
const INSERT_SERVER_URL = "https://jsdb-server-6268???-gre???-uc.a.run.app";
setServerUrl(INSERT_SERVER_URL);

const posts = new DatabaseArray('posts-scrap1');
await posts.push({status: 'PUBLISHED', content: 'JSDB is awesome!', createdDate: new Date()})
```

TypeError: jsdbAxios.defaults.baseURL.replaceAll is not a function
    at startWs (file:///B:/dev/projects/_scrap/jsdb/node_modules/@jsdb/sdk/index.js:20:55)
    at setServerUrl (file:///B:/dev/projects/_scrap/jsdb/node_modules/@jsdb/sdk/index.js:123:9)
    at file:///B:/dev/projects/_scrap/jsdb/src/index.js:4:1
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

Not sure what I'm doing wrong, just took the example from the docs under "Working with Arrays"

**Comment by JpCapdevila** [comment]
Hey @crazy4groovy It should be fixed on the last version of the sdk. And now I have tests :) 

Thanks for your help & sorry for the slow response. Day job responsibilities.
